
lsng:
  sectors:
    - name: Beauty
      url: https://www.lsnglobal.com/sectors/beauty
    - name: Fashion
      url: https://www.lsnglobal.com/sectors/fashion
    - name: Health & Wellness
      url: https://www.lsnglobal.com/sectors/health-wellness
  max_pages: 3

reddit:
  subreddits: [
    femalefashionadvice, malefashionadvice, SkincareAddiction, AsianBeauty, MakeupAddiction,
    fragrance, Perfumes, streetwear, streetwearstartup, frugalmalefashion,
    fashion, malegrooming, Beauty, Futurology, trendanalysis, DataIsBeautiful
  ]
  query: "signals OR trend OR 'future of' OR beauty OR fashion OR wellness OR foresight"
  time_filter: month
  limit: 150

gtrends:
  geo: ES
  tz: 120
  related_queries: true
  keywords: [
    "beauty trends","fashion trends","wellness trends","dopamine dressing","skin cycling","quiet luxury",
    "mob wife aesthetic","clean girl aesthetic","gorpcore","barbiecore","normcore","athleisure",
    "fragrance layering","hair cycling","red light therapy","cold plunge","sleep tourism",
    "quiet quitting fashion","deinfluencing","soft hiking","algae skincare","fermented beauty"
  ]

tiktok:
  hashtags: [
    beauty, fashion, wellness, trendtok, skincare, outfitideas,
    perfumetok, grwm, makeuptutorial, streetwear, fallfashion, fragrance,
    haircare, skincaretips, dupes, corecore, quietluxury
  ]
  max_per_hashtag: 30

rss:
  feeds:
    # Fashion/beauty business & trade
    - https://www.voguebusiness.com/feed/rss
    - https://www.businessoffashion.com/feed
    - https://www.glossy.co/feed/
    - https://www.beautyindependent.com/feed/
    - https://www.beautymatter.com/feed/
    - https://www.cosmeticsdesign-europe.com/Info/Feed
    - https://www.trendhunter.com/rss
    - https://www.springwise.com/feed
    - https://www.psfk.com/feed
    - https://www.dazeddigital.com/rss.xml
    - https://hypebeast.com/feed
    - https://www.highsnobiety.com/rss
    - https://www.allure.com/feed/all/rss
    - https://www.elle.com/rss/all.xml
    - https://www.thecut.com/fashion/rss/index.xml
    # Strategy / foresight / consulting insights
    - https://www.mckinsey.com/feeds/rss/insights
    - https://www.bain.com/insights/rss/
    - https://www.bcg.com/insights/rss
    - https://www.accenture.com/us-en/blogs/blogs-rss
    - https://www.euromonitor.com/feed
    - https://www.kantar.com/uki/rss
    - https://www.wundermanthompson.com/feed
  max_per_feed: 80

substack:
  feeds:
    # Culture / fashion / strategy newsletters
    - https://blackbirdspyplane.substack.com/feed
    - https://leanlux.substack.com/feed
    - https://lineofbeauty.substack.com/feed
    - https://culturestudy.substack.com/feed
    - https://noahpinion.substack.com/feed
    - https://otherinternet.substack.com/feed
    - https://napkinmath.substack.com/feed
    - https://thefutureparty.substack.com/feed
    - https://readmaximums.substack.com/feed
    - https://linernotes.substack.com/feed
    - https://piratewires.substack.com/feed
  max_per_feed: 80
