name: Build CSV daily (branch publish)

on:
  schedule:
    - cron: "0 6 * * *"   # daily 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # so we can commit docs/signals_simple.csv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python build_simple_csv.py
      - name: Commit updated CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update daily signals CSV"
          file_pattern: docs/signals_simple.csv
